export enum EPermission {
  // Permissões de ferramentas
  CREATE_TOOL = "CREATE_TOOL",
  UPDATE_TOOL = "UPDATE_TOOL",
  DELETE_TOOL = "DELETE_TOOL",
  READ_TOOL = "READ_TOOL",

  // Permissões de usuários
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  READ_USER = "READ_USER",

  // Permissões de produtos
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  READ_PRODUCT = "READ_PRODUCT",

  // Permissões de vendas
  CREATE_SALE = "CREATE_SALE",
  UPDATE_SALE = "UPDATE_SALE",
  DELETE_SALE = "DELETE_SALE",
  READ_SALE = "READ_SALE",

  // Permissões de notas fiscais
  CREATE_INVOICE = "CREATE_INVOICE",
  UPDATE_INVOICE = "UPDATE_INVOICE",
  DELETE_INVOICE = "DELETE_INVOICE",
  READ_INVOICE = "READ_INVOICE",
  ISSUE_INVOICE = "ISSUE_INVOICE",

  // Permissões de entradas colheitas ou outros produtos
  CREATE_INPUT_MATERIAL_ENTRY = "CREATE_INPUT_MATERIAL_ENTRY",
  READ_INPUT_MATERIAL_ENTRY = "READ_INPUT_MATERIAL_ENTRY",
  UPDATE_INPUT_MATERIAL_ENTRY = "UPDATE_INPUT_MATERIAL_ENTRY",
  DELETE_INPUT_MATERIAL_ENTRY = "DELETE_INPUT_MATERIAL_ENTRY",

  // Permissões de colheitas
  CREATE_HARVEST = "CREATE_HARVEST",
  UPDATE_HARVEST = "UPDATE_HARVEST",
  DELETE_HARVEST = "DELETE_HARVEST",
  READ_HARVEST = "READ_HARVEST",

  // Permissões de UAP
  CREATE_UAP = "CREATE_UAP",
  UPDATE_UAP = "UPDATE_UAP",
  DELETE_UAP = "DELETE_UAP",
  READ_UAP = "READ_UAP",

  // Ir adicionando conforme necessário
}
